browser/base/content/browser-tabbar.js
Tiny PR to simplify null check
=> [FB] Browser-Tabbar | Simplify null check

browser/base/content/browser-downloadbar.js
This PR cleans-up the downloadbar
=> [FB] Code | Refactor downloadbar

browser/components/FloorpStartup.sys.mjs
---
以下の問題を引き起こしていた可能性のある入れ子になったコメントを除去しました。
https://github.com/Floorp-Projects/Floorp/issues/536
=> [FB] userContent.css | Removed nested comment

browser/components/about/aboutcontributors/contributors.html
I guess since i did some translations in Polish language maybe i can now get on about:contributors... Well maybe.
=> Adding myself into about:contributors

README.md
=> [FB] README | Improve README

browser/base/content/browser-verticaltabs.css
Minor alignment issue
Before:
After:
=> [FB] Vertical Tabs | Bug Fix

browser/base/content/browser-floorp.css, browser/base/content/browser-tabbar.js
Reverts Floorp-Projects/Floorp-core#19
=> Revert "[FB] Code | Made windows draggable"

browser/themes/designs/options/native-verticaltab-hover.css
Reverts Floorp-Projects/Floorp-core#13
=> Revert "Fix: vertical tab bar animation on mouseleave"

browser/base/content/browser-UI-custom.js
Fixes issue [#726](https://github.com/Floorp-Projects/Floorp/issues/726) in the main Floorp Respository.
=> [FB] Bookmarks Toolbar | Bug Fix

browser/components/userjsUtils.sys.mjs
Fix https://github.com/Floorp-Projects/Floorp/issues/708
=> [FB] UserJS | Fix UserJS path

browser/components/jar.mn, browser/components/preferences/jar.mn, browser/components/workspaces/jar.mn
=> fix build error of fast-debug

.gitignore, .vscode/extensions.json
VSCodeの推奨拡張機能を設定しました。
また、`.vscode`内の他のファイル(`.vscode/settings.json`等)を除外するように設定しました。
=> [FB] Dev | Add recommended extension settings for vscode

browser/components/jar.mn, browser/components/preferences/jar.mn, browser/components/workspaces/jar.mn
Reverts Floorp-Projects/Floorp-core#37
=> Revert "fix build error of fast-debug"

browser/components/preferences/notes.js
This PR modernizes notes codebase
=> [FB] Notes | Modernize codebase

browser/app/profile/000-floorp.js
Removes ads in about:protection
=> [FB] Protections | Remove ads

browser/base/content/browser-floorp.css, browser/base/content/browser-webpanel.inc.xhtml
Add button to hide browser manager sidebar.
=> [FB] BMS | Add button to hide sidebar

.github/workflows/update-submodule.yml, .github/workflows/user-agent_scrape.yml
Related: Floorp-Projects/Floorp#938
=> [FB] Workflow | Update action version

browser/base/content/browser-verticaltabs.js
Resolves: https://github.com/Floorp-Projects/Floorp/discussions/941
=> [FB] VerticalTab | Allow dragging window

browser/components/preferences/dialogs/manageWorkspace.js, browser/components/welcome/welcome.html
(PR created because I do not have write permission to localisation repository)
Continuation of commit e5c92d0 to fix #28 
Together with [#52](https://github.com/Floorp-Projects/Unified-l10n-central/pull/52) in localisation repository.
=> [FB] Code | Fix typos 2

browser/base/content/browser-ssb-support.mjs, browser/base/content/modules/ssb/SiteSpecificBrowserService.mjs
=> [FB] SSB | LocalHost Support

browser/base/content/browser-ssb-support.mjs, browser/base/content/modules/ssb/SiteSpecificBrowserService.mjs
Reverts Floorp-Projects/Floorp-core#72
正常に動作しないことを見逃していたためRevert
=> Revert "[FB] SSB | LocalHost Support"

browser/base/content/browser-ssb-support.mjs, browser/base/content/modules/ssb/SiteSpecificBrowserService.mjs
個人的に使いたかったので追加しました、チェックに正規表現使ってるので要修正かも
=> [FB] SSB | localhostのサポートを追加

browser/app/profile/000-floorp.js, browser/base/content/browser-manager-sidebar.mjs
Add Custom keyboard shortcut option to fully hide the browser manager sidebar. 
[Discord user request: https://discord.com/channels/877135925707173889/1242797124098199582/1242797124098199582 ]
=> [FB] CSK | Add shortcut to toggle full BMS visibility

nora/.gitignore, nora/dist/jar.mn, nora/package.json, nora/pnpm-lock.yaml, nora/scripts/gen_jarmn.ts, nora/vite.config.ts, package.json, pnpm-lock.yaml
=> [FB] Build | add puppeteer to launch browser

nora/src/components/custom-shortcut-key/index.ts, nora/src/preferences/csk/setkey.ts
fix Floorp-Projects/Floorp#1240
=> [FB] Nora CSK | fix can't delete key setting
